---
- name: Install Dependances
  include_tasks: "{{ item }}.yml"
  with_items:
    - dependences

- name: Generate Configuration
  include_tasks: "{{ item }}.yml"
  with_items:
    - config

- name: Create Containers
  include_tasks: "{{ item }}.yml"
  with_items:
    - traefik
